---
# tasks file for config_apache
- name: download maven artifact
  maven_artifact:
    group_id: org.jenkins.main 
    artifact_id: jenkins-war
    version: latest
    extension: war
    repository_url: 'http://192.168.1.2:8081/repository/nexusrep/'
    username: admin
    password: admin
    dest: /home/benjixxx/peaceful

- name: changer la permisssion du fichier war de destination
  shell: sudo chmod 755  /home/benjixxx/peaceful/*.war

- name: tomcat container
  docker_container:
    name: tomcat
    image: tomcat:8.0
    state: started
    ports:
    - 8889:8080
    volumes:
    - /home/benjixxx/peaceful/:/usr/local/tomcat/webapps/